title: Dean Kolk # your name (or website title) here
logo: "/images/Kolk.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Scientist who is passionate about solving complex problems with creative solutions. Bachelor's in Statistics from Elon University, and current Master's Candidate at the Institute for Advanced Analytics. 
  <br><br>

  <a href="https://www.linkedin.com/in/deankolk/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
